name: CI/Build Docker Image From Tag And Repository

on:
  workflow_call:
    inputs:
      dockerfile:
        description: "The path to the Dockerfile"
        required: false
        type: string
        default: "Dockerfile"
      context:
        description: "The build directory of the image"
        required: false
        type: string
        default: "."
      image-name:
        required: true
        type: string
        description: "The name of the image"
      build-args:
        required: false
        type: string
        description: "List of build args"
      tag:
        required: false
        type: string
        description: "The git tag to checkout"
      repository:
        required: false
        type: string
        description: "The repository to checkout"
    secrets:
      CONTAINER_REGISTRY_TOKEN:
        required: true
      CONTAINER_REGISTRY_USERNAME:
        required: true
      CONTAINER_REGISTRY_ENDPOINT:
        required: true
      PAT:
        required: true

  workflow_dispatch:
    inputs:
      dockerfile:
        description: "The path to the Dockerfile"
        required: false
        type: string
        default: "Dockerfile"
      context:
        description: "The build directory of the image"
        required: false
        type: string
        default: "."
      image-name:
        required: true
        type: string
        description: "The name of the image"
      build-args:
        required: false
        type: string
        description: "List of build args"
      tag:
        required: false
        type: string
        description: "The git tag to checkout"
      repository:
        required: true
        type: string
        description: "The repository to checkout"

jobs:
  docker-build-and-push:
    name: Docker build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          repository: ${{ inputs.repository }}
          token: ${{ secrets.PAT }}
          fetch-tags: true
          fetch-depth: 0
      - name: Add Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/${{ inputs.image-name }}
          tags: |
            latest
            ${{ inputs.tag }}
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-and-push@v5
        with:
          file: ${{ inputs.dockerfile }}
          context: ${{ inputs.context }}
          # hack https://github.com/docker/build-push-action/issues/773
          provenance: false
          build-args: ${{ inputs.build-args }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # hack, disk problems
          cache-from: type=gha,scope=${{ inputs.repository }}/${{ inputs.image-name }}:buildcache
          cache-to: type=gha,mode=max,scope=${{ inputs.repository }}/${{ inputs.image-name }}:buildcache
